apiVersion: v1
kind: Service
metadata:
  name: tc-listener-order-service
  namespace: namespace-tc
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30001
  selector:
    app: tc-listener-order-service
